// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pb-example.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // ใช้ส่งค่า ID ของผู้ใช้
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonRequest) Reset() {
	*x = PersonRequest{}
	mi := &file_pb_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonRequest) ProtoMessage() {}

func (x *PersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonRequest.ProtoReflect.Descriptor instead.
func (*PersonRequest) Descriptor() ([]byte, []int) {
	return file_pb_example_proto_rawDescGZIP(), []int{0}
}

func (x *PersonRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`   // ชื่อของผู้ใช้
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`      // ID ของผู้ใช้
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"` // อีเมลของผู้ใช้
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonResponse) Reset() {
	*x = PersonResponse{}
	mi := &file_pb_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonResponse) ProtoMessage() {}

func (x *PersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonResponse.ProtoReflect.Descriptor instead.
func (*PersonResponse) Descriptor() ([]byte, []int) {
	return file_pb_example_proto_rawDescGZIP(), []int{1}
}

func (x *PersonResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PersonResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type InsertPersonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNo       string                 `protobuf:"bytes,3,opt,name=phone_no,json=phoneNo,proto3" json:"phone_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertPersonRequest) Reset() {
	*x = InsertPersonRequest{}
	mi := &file_pb_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertPersonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertPersonRequest) ProtoMessage() {}

func (x *InsertPersonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertPersonRequest.ProtoReflect.Descriptor instead.
func (*InsertPersonRequest) Descriptor() ([]byte, []int) {
	return file_pb_example_proto_rawDescGZIP(), []int{2}
}

func (x *InsertPersonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InsertPersonRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InsertPersonRequest) GetPhoneNo() string {
	if x != nil {
		return x.PhoneNo
	}
	return ""
}

type InsertPersonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNo       string                 `protobuf:"bytes,4,opt,name=phone_no,json=phoneNo,proto3" json:"phone_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertPersonResponse) Reset() {
	*x = InsertPersonResponse{}
	mi := &file_pb_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertPersonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertPersonResponse) ProtoMessage() {}

func (x *InsertPersonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertPersonResponse.ProtoReflect.Descriptor instead.
func (*InsertPersonResponse) Descriptor() ([]byte, []int) {
	return file_pb_example_proto_rawDescGZIP(), []int{3}
}

func (x *InsertPersonResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InsertPersonResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InsertPersonResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InsertPersonResponse) GetPhoneNo() string {
	if x != nil {
		return x.PhoneNo
	}
	return ""
}

var File_pb_example_proto protoreflect.FileDescriptor

const file_pb_example_proto_rawDesc = "" +
	"\n" +
	"\x10pb-example.proto\x12\aexample\"\x1f\n" +
	"\rPersonRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"J\n" +
	"\x0ePersonResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"Z\n" +
	"\x13InsertPersonRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x19\n" +
	"\bphone_no\x18\x03 \x01(\tR\aphoneNo\"k\n" +
	"\x14InsertPersonResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x19\n" +
	"\bphone_no\x18\x04 \x01(\tR\aphoneNo2\x94\x01\n" +
	"\vUserService\x12:\n" +
	"\aGetUser\x12\x16.example.PersonRequest\x1a\x17.example.PersonResponse\x12I\n" +
	"\n" +
	"InsertUser\x12\x1c.example.InsertPersonRequest\x1a\x1d.example.InsertPersonResponseB\x1eZ\x1cgo-poc-grpc/pb-example/protob\x06proto3"

var (
	file_pb_example_proto_rawDescOnce sync.Once
	file_pb_example_proto_rawDescData []byte
)

func file_pb_example_proto_rawDescGZIP() []byte {
	file_pb_example_proto_rawDescOnce.Do(func() {
		file_pb_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_example_proto_rawDesc), len(file_pb_example_proto_rawDesc)))
	})
	return file_pb_example_proto_rawDescData
}

var file_pb_example_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_example_proto_goTypes = []any{
	(*PersonRequest)(nil),        // 0: example.PersonRequest
	(*PersonResponse)(nil),       // 1: example.PersonResponse
	(*InsertPersonRequest)(nil),  // 2: example.InsertPersonRequest
	(*InsertPersonResponse)(nil), // 3: example.InsertPersonResponse
}
var file_pb_example_proto_depIdxs = []int32{
	0, // 0: example.UserService.GetUser:input_type -> example.PersonRequest
	2, // 1: example.UserService.InsertUser:input_type -> example.InsertPersonRequest
	1, // 2: example.UserService.GetUser:output_type -> example.PersonResponse
	3, // 3: example.UserService.InsertUser:output_type -> example.InsertPersonResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_example_proto_init() }
func file_pb_example_proto_init() {
	if File_pb_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_example_proto_rawDesc), len(file_pb_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_example_proto_goTypes,
		DependencyIndexes: file_pb_example_proto_depIdxs,
		MessageInfos:      file_pb_example_proto_msgTypes,
	}.Build()
	File_pb_example_proto = out.File
	file_pb_example_proto_goTypes = nil
	file_pb_example_proto_depIdxs = nil
}
